server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location = / {
        return 302 /md/;
    }

    location /md/ {
        try_files $uri $uri/ /md/index.html;
    }

    location ~* ^/md/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    access_log off;
    error_log /dev/null;
}
